const fs = require("fs");
const path = require("path");

const env = {
  production: true,
  emailjs: {
    publicKey: process.env.EMAILJS_PUBLIC_KEY || "",
    serviceId: process.env.EMAILJS_SERVICE_ID || "",
    templateId: process.env.EMAILJS_TEMPLATE_ID || "",
  },
};

const content = `// Auto-generated by set-env.js — do not edit
export const environment = ${JSON.stringify(env, null, 2)};
`;

const filePath = path.join(
  __dirname,
  "../src/environments/environment.prod.ts",
);
fs.writeFileSync(filePath, content);
console.log("✅ environment.prod.ts generated");
